### PR TITLE
309 rubocop all things

### PR DESCRIPTION
**Pull request by faithngetich**
closes [Issue 309](https://github.com/roschaefer/rundfunk-mitbestimmen/issues/309)

### CODE REVIEW

**Comment by roschaefer** [comment]
@faithngetich you could also make a rake task for `brakeman` and include it in `bundle exec rake`

**Comment by roschaefer** [comment]
@faithngetich I think you did not `git push` or did you?

**Comment by faithngetich** [comment]
@roschaefer not yet, I have not implemented the changes yet. I'll let you know once I have.

**Comment by roschaefer** [comment]
You *could* merge it now.

**Comment by faithngetich** [comment]
@roschaefer I see you have suggested that I merge it, how about this comment?
```@faithngetich you could also make a rake task for brakeman and include it in bundle exec rake```

**Comment by roschaefer** [comment]
@faithngetich that's a *could*. You can integrate it but you don't have to. The important part is: `rubocop`, `brakeman` and `rspec` should be executed on the build server and that's the case already. You can put it all in one rake task but you don't have to.

**Comment by roschaefer** [comment]
@faithngetich it's good practice to keep PRs small

If you still want to do the rake thing, feel free to open another PR :wink:

**Pull request merged**
