### PR TITLE
[WIP] 847 create some historical data in our seed data

### PR DESCRIPTION
**Pull request by aonomike**
Add broadcast and impression data from seed file
#### Motivation and Context

To create dummy data for development purposes

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by aonomike** [comment]
Currently I get the error below when I run `ember s` and try accessing `localhost:4200`

```SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at VMSandbox.eval (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/ember-app.js:163:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/ember-app.js:160:18)
    at EmberApp.retrieveSandboxedApp (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli-fastboot/index.js:319:29)
    at Layer.handle [as handle_request] (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/express/lib/router/index.js:317:13)
    at /Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/globalprograms/Work/opensource/agile-ventures/rundfunk-mitbestimmen/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)```

**Comment by mattwr18** [comment]
have updated this to remove changes not associated with the ticket @aonomike @roschaefer

**Comment by aonomike** [comment]
@roschaefer I have corrected rubocop

**Comment by roschaefer** [comment]
@aonomike excellent! Thank you for your contribution!

**Pull request merged**
