### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by roschaefer**

### CODE REVIEW

**Comment by greysteil** [comment]
Hey, looks like you're already pretty up-to-date after this, but would you be up for automatically creating dependency update PRs in future? I built [Dependabot](https://dependabot.com) to do that at my last company, and we made it free for open source. Could be a time-saver? Trying to get as many people using it as possible so the [compatibility scores](https://dependabot.com/compatibility-score.html) are robust.

**Comment by roschaefer** [comment]
Nice, I was looking for sth. just like that. I'll have a look into this and tell you if this meets our requirements.

**Comment by greysteil** [comment]
Awesome - feedback always appreciated!

**Comment by roschaefer** [comment]
```
Dependabot can't evaluate your Ruby dependency files.

As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.

This is almost always caused by one of your dependency files loading in other files, which Dependabot doesn't currently support. If moving your dependency definitions into a single file isn't an option, let us know.

```
There we go. We have a repository containing a `/frontend` (npm/yarn dependencies), a `/backend` folder (ruby dependencies) and a `/` folder for fullstack testing. We're loading the rails environment (access to the database) and therefore we load the `Gemfile` under `/backend`.

:cry: :tired_face: :sob:

**Comment by greysteil** [comment]
Drat! Just saw in https://github.com/roschaefer/rundfunk-mitbestimmen/issues/252.

Dependabot doesn't support `eval_gemfile` yet. I could add it, but supporting having two `Gemfile.lock`s might be tricky. I'll have a think.

😢

**Pull request merged**
