### PR TITLE
Landing page improvements

### PR DESCRIPTION
**Pull request by roschaefer**

### CODE REVIEW

**Comment by somamo** [comment]
@roschaefer The new version of the landing page is cool. I attached some little style change. 

I think a second fresh colour like #a0b700 lets the design look more modern. The new colour should be used also for the sub pages. 

screen shot 2017-10-10 at 13 21 08

The design looks cleaner if you would use four columns instead if two.
screen shot 2017-10-10 at 13 15 45

The icons should get smaller. For the screenshot I used the width of 70 px. 
screen shot 2017-10-10 at 13 07 43

**Comment by roschaefer** [comment]
@somamo thanks a lot, feel free to push the changed layout!

I'm OK to change the colour, but I would prefer to have a consistent `primary` colour across the entire application. I will check Semantic UI and see how a new primary colour looks like.

**Comment by roschaefer** [comment]
@somamo Maybe we can try out a change of the primary colour in #311 too. I'll leave it here for now, to make the PR merge-ready.

**Comment by somamo** [comment]
@roschaefer What about this icons?
screen shot 2017-10-10 at 13 07 43
They look better with the width of 70 - 80 px.

**Comment by somamo** [comment]
@roschaefer The button on the start page is a special button, it`s an eye catcher, so it is ok to use this colour once. The same is with other elements on the start page.  Nonetheless the tone of primary blue is old-fashioned.

**Pull request merged**
