### PR TITLE
Embedded Youtube Video on Start Page: Add a description and translations

### PR DESCRIPTION
**Pull request by roschaefer**
To youtube playlist on our landing page. @lindseyperry have a look in "Files changed".

@mattwr18 I was considering to add a youtube placeholder with a clickable link for data privacy. Similar to the twitter button below. We could use a thumbnail of a video. Does that sound like an idea?

### CODE REVIEW

**Comment by mattwr18** [comment]
hey @roschaefer I like your idea above! Data privacy is always something to keep in mind! 
As far as the code, I would either need to pull down the code to see how it looks, or trust that it probably looks good. Maybe you could provide a screenshot? I;m sure it looks good though. 

I like that you used a percentage for the padding-bottom!

**Comment by roschaefer** [comment]
@mattwr18 not me, but https://avexdesigns.com/responsive-youtube-embed/

**Comment by mattwr18** [comment]
hey sorry, I clicked on squash and merge, but didn't confirm merge :(

**Comment by roschaefer** [comment]
no worries it's merged :slightly_smiling_face:

**Pull request merged**
