### PR TITLE
created route /data-privacy and copy pasted data privacy statement

### LINKED ISSUE #127: Add separate data privacy statement
See [here](https://www.e-recht24.de/news/datenschutz/7679-vorsicht-abmahnung-versteckte-datenschutzerklaerungen-sind-abmahnfaehig.html) and [here](http://kanzlei-lachenmann.de/einzelner-punkt-ist-noetig-fuer-datenschutzerklaerung-homepage/).

### PR DESCRIPTION
**Pull request by roschaefer**
close #127

### CODE REVIEW

**Comment by roschaefer** [comment]
@somamo imprint and data-privacy statement is German-only and most of the data privacy statement is copy-pasted from [here](https://www.e-recht24.de/muster-datenschutzerklaerung.html). The stacking of the link-menu in the footer is sometimes 3+1 instead 2+2 which I would prefer. Do you think we should translate imprint and data-privacy statement? Do you think we should explain *where* our data is stored (Frankfurt a. M. and Dublin)?

**Comment by roschaefer** [comment]
oh and Do you think it's a problem if we use formal `Sie` instead of colloquial `Du`? :smile_cat:

**Comment by somamo** [comment]
@roschaefer I think it is ok if we translate the text later. In this case I prefer to use formal "Sie".

**Comment by somamo** [comment]
@roschaefer We already explain where our data is stored in FAQ. I think that's quite enough.

**Pull request merged**
